name: rpchat
version: '1.2.2'
main: work.dvdd.rpchat.Core
api-version: '1.20'
authors: [ realdivided ]
description: A plugin for Role Play commands for your Minecraft server.
website: https://dvdd.work